// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuQaQONDWY19LKVcwqcKZ8SqU53AaFd0',
    appId: '1:542302591162:web:7ad42a1f0b32dafab38a83',
    messagingSenderId: '542302591162',
    projectId: 'greenchargehub01',
    authDomain: 'greenchargehub01.firebaseapp.com',
    storageBucket: 'greenchargehub01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPPuzmO_WLC4uK9IkAqCAKXf-9nJbMhts',
    appId: '1:542302591162:android:d4051871d4bb41ccb38a83',
    messagingSenderId: '542302591162',
    projectId: 'greenchargehub01',
    storageBucket: 'greenchargehub01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4-oV1TRcBH-DTRS9ZagQWlBUA83acbiQ',
    appId: '1:542302591162:ios:ffb3c7f1afdf9408b38a83',
    messagingSenderId: '542302591162',
    projectId: 'greenchargehub01',
    storageBucket: 'greenchargehub01.appspot.com',
    iosBundleId: 'com.example.greenchargehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4-oV1TRcBH-DTRS9ZagQWlBUA83acbiQ',
    appId: '1:542302591162:ios:1db460b7fdaabd55b38a83',
    messagingSenderId: '542302591162',
    projectId: 'greenchargehub01',
    storageBucket: 'greenchargehub01.appspot.com',
    iosBundleId: 'com.example.greenchargehub.RunnerTests',
  );
}
